# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wei/VsCode/cmakeLearn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wei/VsCode/cmakeLearn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wei/VsCode/cmakeLearn/CMakeFiles /home/wei/VsCode/cmakeLearn//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wei/VsCode/cmakeLearn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libmath

# Build rule for target.
libmath: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libmath
.PHONY : libmath

# fast build rule for target.
libmath/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libmath.dir/build.make CMakeFiles/libmath.dir/build
.PHONY : libmath/fast

#=============================================================================
# Target rules for targets named libstat

# Build rule for target.
libstat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libstat
.PHONY : libstat

# fast build rule for target.
libstat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstat.dir/build.make CMakeFiles/libstat.dir/build
.PHONY : libstat/fast

#=============================================================================
# Target rules for targets named learn

# Build rule for target.
learn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 learn
.PHONY : learn

# fast build rule for target.
learn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learn.dir/build.make CMakeFiles/learn.dir/build
.PHONY : learn/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learn.dir/build.make CMakeFiles/learn.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learn.dir/build.make CMakeFiles/learn.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learn.dir/build.make CMakeFiles/learn.dir/main.c.s
.PHONY : main.c.s

math/math.o: math/math.c.o
.PHONY : math/math.o

# target to build an object file
math/math.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libmath.dir/build.make CMakeFiles/libmath.dir/math/math.c.o
.PHONY : math/math.c.o

math/math.i: math/math.c.i
.PHONY : math/math.i

# target to preprocess a source file
math/math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libmath.dir/build.make CMakeFiles/libmath.dir/math/math.c.i
.PHONY : math/math.c.i

math/math.s: math/math.c.s
.PHONY : math/math.s

# target to generate assembly for a file
math/math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libmath.dir/build.make CMakeFiles/libmath.dir/math/math.c.s
.PHONY : math/math.c.s

stat/stat.o: stat/stat.c.o
.PHONY : stat/stat.o

# target to build an object file
stat/stat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstat.dir/build.make CMakeFiles/libstat.dir/stat/stat.c.o
.PHONY : stat/stat.c.o

stat/stat.i: stat/stat.c.i
.PHONY : stat/stat.i

# target to preprocess a source file
stat/stat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstat.dir/build.make CMakeFiles/libstat.dir/stat/stat.c.i
.PHONY : stat/stat.c.i

stat/stat.s: stat/stat.c.s
.PHONY : stat/stat.s

# target to generate assembly for a file
stat/stat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstat.dir/build.make CMakeFiles/libstat.dir/stat/stat.c.s
.PHONY : stat/stat.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... learn"
	@echo "... libmath"
	@echo "... libstat"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... math/math.o"
	@echo "... math/math.i"
	@echo "... math/math.s"
	@echo "... stat/stat.o"
	@echo "... stat/stat.i"
	@echo "... stat/stat.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

